// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj8EawFbbd1e7BARRmzARLm1qCq6n_0AY',
    appId: '1:889188494167:web:a72bc091cdcc5d9cd02c12',
    messagingSenderId: '889188494167',
    projectId: 'pakistan-voting-system',
    authDomain: 'pakistan-voting-system.firebaseapp.com',
    storageBucket: 'pakistan-voting-system.appspot.com',
    measurementId: 'G-L0ZH6PE9WL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgW-QLaxYL3YH97FqGSmIWq4W_QlxphgI',
    appId: '1:889188494167:android:a4fab16090e22c0ed02c12',
    messagingSenderId: '889188494167',
    projectId: 'pakistan-voting-system',
    storageBucket: 'pakistan-voting-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI527k1FYH8_r6gmzei8lMlFjW5cowcss',
    appId: '1:889188494167:ios:c189cc5ad72db7d5d02c12',
    messagingSenderId: '889188494167',
    projectId: 'pakistan-voting-system',
    storageBucket: 'pakistan-voting-system.appspot.com',
    iosClientId: '889188494167-um14gi8dkc60c2mk5lg7fogaht28nsgd.apps.googleusercontent.com',
    iosBundleId: 'com.example.votingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI527k1FYH8_r6gmzei8lMlFjW5cowcss',
    appId: '1:889188494167:ios:c189cc5ad72db7d5d02c12',
    messagingSenderId: '889188494167',
    projectId: 'pakistan-voting-system',
    storageBucket: 'pakistan-voting-system.appspot.com',
    iosClientId: '889188494167-um14gi8dkc60c2mk5lg7fogaht28nsgd.apps.googleusercontent.com',
    iosBundleId: 'com.example.votingSystem',
  );
}
